
import { Movie } from './types';

export const MOCK_MOVIES: Movie[] = [
  {
    id: '1',
    title: 'Interstellar',
    genres: ['Sci-Fi', 'Drama', 'Adventure'],
    rating: 10,
    tmdbRating: 8.7,
    releaseDate: '2014-11-07',
    overview: 'The adventures of a group of explorers who make use of a newly discovered wormhole to surpass the limitations on human space travel and conquer the vast distances involved in an interstellar voyage.',
    posterUrl: 'https://picsum.photos/seed/m1/600/900',
    status: 'watched',
    addedAt: '2023-10-01',
  },
  {
    id: '2',
    title: 'Inception',
    genres: ['Sci-Fi', 'Action', 'Thriller'],
    rating: 9,
    tmdbRating: 8.8,
    releaseDate: '2010-07-16',
    overview: 'Cobb, a skilled thief who commits corporate espionage by infiltrating the subconscious of his targets is offered a chance to regain his old life as payment for a task considered to be impossible: "inception", the implantation of another person\'s idea into a target\'s subconscious.',
    posterUrl: 'https://picsum.photos/seed/m2/600/900',
    status: 'watched',
    addedAt: '2023-10-05',
  },
  {
    id: '3',
    title: 'The Dark Knight',
    genres: ['Action', 'Crime', 'Drama'],
    rating: 10,
    tmdbRating: 9.0,
    releaseDate: '2008-07-18',
    overview: 'Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations that plague the streets. The partnership proves to be effective, but they soon find themselves prey to a reign of chaos unleashed by a rising criminal mastermind known to the terrified citizens of Gotham as the Joker.',
    posterUrl: 'https://picsum.photos/seed/m3/600/900',
    status: 'watched',
    addedAt: '2023-11-12',
  },
  {
    id: '4',
    title: 'Pulp Fiction',
    genres: ['Thriller', 'Crime'],
    rating: 8,
    tmdbRating: 8.9,
    releaseDate: '1994-10-14',
    overview: "A burger-loving hit man, his philosophical partner, a drug-addled gangster's moll and a washed-up boxer converge in this sprawling, comedic crime caper. Their adventures unfurl in three stories that intertwine in cinematic ingenuity.",
    posterUrl: 'https://picsum.photos/seed/m4/600/900',
    status: 'watchlist',
    addedAt: '2024-01-20',
  },
  {
    id: '5',
    title: 'Parasite',
    genres: ['Thriller', 'Mystery', 'Drama'],
    rating: 0,
    tmdbRating: 8.5,
    releaseDate: '2019-05-30',
    overview: "All unemployed, Ki-taek's family takes peculiar interest in the wealthy and glamorous Parks for their livelihood until they get entangled in an unexpected incident.",
    posterUrl: 'https://picsum.photos/seed/m5/600/900',
    status: 'watchlist',
    addedAt: '2024-02-15',
  },
];
