import { Movie } from './types';

export const MOCK_MOVIES: any[] = [
  {
    id: '1',
    title: 'Interstellar',
    genres: ['Sci-Fi', 'Drama', 'Adventure'],
    rating: 10,
    tmdbRating: 8.7,
    releaseDate: '2014-11-07',
    overview: 'The adventures of a group of explorers who make use of a newly discovered wormhole to surpass the limitations on human space travel and conquer the vast distances involved in an interstellar voyage.',
    posterUrl: 'https://picsum.photos/seed/m1/600/900',
    status: 'watched',
    addedAt: '2023-10-01',
  },
  {
    id: '2',
    title: 'Inception',
    genres: ['Sci-Fi', 'Action', 'Thriller'],
    rating: 9,
    tmdbRating: 8.8,
    releaseDate: '2010-07-16',
    overview: 'Cobb, a skilled thief who commits corporate espionage by infiltrating the subconscious of his targets is offered a chance to regain his old life as payment for a task considered to be impossible: "inception", the implantation of another person\'s idea into a target\'s subconscious.',
    posterUrl: 'https://picsum.photos/seed/m2/600/900',
    status: 'watched',
    addedAt: '2023-10-05',
  },
  {
    id: '3',
    title: 'The Dark Knight',
    genres: ['Action', 'Crime', 'Drama'],
    rating: 10,
    tmdbRating: 9.0,
    releaseDate: '2008-07-18',
    overview: 'Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations that plague the streets.',
    posterUrl: 'https://picsum.photos/seed/m3/600/900',
    status: 'watched',
    addedAt: '2023-11-12',
  },
  {
    id: '4',
    title: 'Pulp Fiction',
    genres: ['Thriller', 'Crime'],
    rating: 8,
    tmdbRating: 8.9,
    releaseDate: '1994-10-14',
    overview: "A burger-loving hit man, his philosophical partner, a drug-addled gangster's moll and a washed-up boxer converge in this sprawling, comedic crime caper.",
    posterUrl: 'https://picsum.photos/seed/m4/600/900',
    status: 'watchlist',
    addedAt: '2024-01-20',
  },
  {
    id: '5',
    title: 'Parasite',
    genres: ['Thriller', 'Mystery', 'Drama'],
    rating: 0,
    tmdbRating: 8.5,
    releaseDate: '2019-05-30',
    overview: "All unemployed, Ki-taek's family takes peculiar interest in the wealthy and glamorous Parks for their livelihood until they get entangled in an unexpected incident.",
    posterUrl: 'https://picsum.photos/seed/m5/600/900',
    status: 'watchlist',
    addedAt: '2024-02-15',
  },
  {
    id: '6',
    title: 'Beyond the Horizon',
    genres: ['Sci-Fi', 'Adventure'],
    rating: 0,
    tmdbRating: 7.2,
    releaseDate: '2025-12-12',
    overview: "In a world where the stars are fading, one crew sets out on a final mission to find a new sun.",
    posterUrl: 'https://picsum.photos/seed/m6/600/900',
    status: 'none',
    addedAt: '2024-03-01',
  },
  {
    id: '7',
    title: 'Shadow of the Empire',
    genres: ['Action', 'Fantasy'],
    rating: 0,
    tmdbRating: 6.8,
    releaseDate: '2026-05-24',
    overview: "A forgotten heir must reclaim a throne lost to darkness centuries ago.",
    posterUrl: 'https://picsum.photos/seed/m7/600/900',
    status: 'none',
    addedAt: '2024-03-05',
  },
  {
    id: '8',
    title: 'The Godfather',
    genres: ['Crime', 'Drama'],
    rating: 10,
    tmdbRating: 9.2,
    releaseDate: '1972-03-14',
    overview: "Spanning the years 1945 to 1955, a chronicle of the fictional Italian-American Corleone crime family.",
    posterUrl: 'https://picsum.photos/seed/m8/600/900',
    status: 'watched',
    addedAt: '2023-05-10',
  },
  {
    id: '9',
    title: 'The Matrix',
    genres: ['Sci-Fi', 'Action'],
    rating: 9,
    tmdbRating: 8.7,
    releaseDate: '1999-03-31',
    overview: "Set in the 22nd century, The Matrix tells the story of a computer hacker who joins a group of underground insurgents fighting the vast and powerful computers who now rule the earth.",
    posterUrl: 'https://picsum.photos/seed/m9/600/900',
    status: 'watched',
    addedAt: '2023-06-15',
  },
  {
    id: '10',
    title: 'Spirited Away',
    genres: ['Animation', 'Fantasy', 'Adventure'],
    rating: 10,
    tmdbRating: 8.6,
    releaseDate: '2001-07-20',
    overview: "A young girl, Chihiro, becomes trapped in a strange new world of spirits. When her parents undergo a mysterious transformation, she must call upon the courage she never knew she had to free her family.",
    posterUrl: 'https://picsum.photos/seed/m10/600/900',
    status: 'watched',
    addedAt: '2023-07-20',
  },
  {
    id: '11',
    title: 'Mad Max: Fury Road',
    genres: ['Action', 'Adventure', 'Sci-Fi'],
    rating: 9,
    tmdbRating: 8.1,
    releaseDate: '2015-05-15',
    overview: "In a post-apocalyptic wasteland, a woman rebels against a tyrannical ruler in search for her homeland with the aid of a group of female prisoners, a psychotic worshiper, and a drifter named Max.",
    posterUrl: 'https://picsum.photos/seed/m11/600/900',
    status: 'watched',
    addedAt: '2023-08-05',
  },
  {
    id: '12',
    title: 'La La Land',
    genres: ['Comedy', 'Drama', 'Music'],
    rating: 8,
    tmdbRating: 7.9,
    releaseDate: '2016-12-09',
    overview: "While navigating their separate careers in Los Angeles, a pianist and an actress fall in love while attempting to reconcile their aspirations for the future.",
    posterUrl: 'https://picsum.photos/seed/m12/600/900',
    status: 'watchlist',
    addedAt: '2024-01-05',
  },
  {
    id: '13',
    title: 'The Shawshank Redemption',
    genres: ['Drama', 'Crime'],
    rating: 10,
    tmdbRating: 9.3,
    releaseDate: '1994-09-22',
    overview: "Framed in the 1940s for the double murder of his wife and her lover, upstanding banker Andy Dufresne begins a new life at the Shawshank prison, where he puts his accounting skills to work for an amoral warden.",
    posterUrl: 'https://picsum.photos/seed/m13/600/900',
    status: 'watched',
    addedAt: '2023-04-12',
  },
  {
    id: '14',
    title: 'Blade Runner 2049',
    genres: ['Sci-Fi', 'Drama', 'Mystery'],
    rating: 9,
    tmdbRating: 8.0,
    releaseDate: '2017-10-06',
    overview: "Thirty years after the events of the first film, a new blade runner, LAPD Officer K, unearths a long-buried secret that has the potential to plunge what's left of society into chaos.",
    posterUrl: 'https://picsum.photos/seed/m14/600/900',
    status: 'watched',
    addedAt: '2023-09-22',
  },
  {
    id: '15',
    title: 'Arrival',
    genres: ['Sci-Fi', 'Drama', 'Mystery'],
    rating: 9,
    tmdbRating: 7.9,
    releaseDate: '2016-11-11',
    overview: "Taking place after alien spacecraft land around the world, a linguistics expert is recruited by the military to determine whether they come in peace or are a threat.",
    posterUrl: 'https://picsum.photos/seed/m15/600/900',
    status: 'watched',
    addedAt: '2023-11-01',
  },
  {
    id: '16',
    title: 'Dune: Part Two',
    genres: ['Sci-Fi', 'Adventure', 'Action'],
    rating: 10,
    tmdbRating: 8.8,
    releaseDate: '2024-03-01',
    overview: "Follow the mythic journey of Paul Atreides as he unites with Chani and the Fremen while on a path of revenge against the conspirators who destroyed his family.",
    posterUrl: 'https://picsum.photos/seed/m16/600/900',
    status: 'watched',
    addedAt: '2024-03-02',
  },
  {
    id: '17',
    title: 'Spider-Man: Across the Spider-Verse',
    genres: ['Animation', 'Action', 'Adventure'],
    rating: 10,
    tmdbRating: 8.7,
    releaseDate: '2023-06-02',
    overview: "After reuniting with Gwen Stacy, Brooklyn’s full-time, friendly neighborhood Spider-Man is catapulted across the Multiverse, where he encounters a team of Spider-People charged with protecting its very existence.",
    posterUrl: 'https://picsum.photos/seed/m17/600/900',
    status: 'watched',
    addedAt: '2023-06-05',
  },
  {
    id: '18',
    title: 'The Grand Budapest Hotel',
    genres: ['Comedy', 'Drama'],
    rating: 9,
    tmdbRating: 8.1,
    releaseDate: '2014-02-26',
    overview: "The adventures of Gustave H, a legendary concierge at a famous European hotel between the wars, and Zero Moustafa, the lobby boy who becomes his most trusted friend.",
    posterUrl: 'https://picsum.photos/seed/m18/600/900',
    status: 'watched',
    addedAt: '2023-10-15',
  },
  {
    id: '19',
    title: 'Everything Everywhere All At Once',
    genres: ['Action', 'Adventure', 'Sci-Fi'],
    rating: 10,
    tmdbRating: 7.8,
    releaseDate: '2022-03-24',
    overview: "An aging Chinese immigrant is swept up in an insane adventure, where she alone can save the world by exploring other universes connecting with the lives she could have led.",
    posterUrl: 'https://picsum.photos/seed/m19/600/900',
    status: 'watched',
    addedAt: '2023-11-20',
  },
  {
    id: '20',
    title: 'Gladiator II',
    genres: ['Action', 'Adventure', 'Drama'],
    rating: 0,
    tmdbRating: 7.5,
    releaseDate: '2024-11-22',
    overview: "Follow Lucius, the son of Lucilla, who as a young man was saved by Maximus during the events of the original Gladiator.",
    posterUrl: 'https://picsum.photos/seed/m20/600/900',
    status: 'watchlist',
    addedAt: '2024-04-01',
  }
];
